### ISSUE TITLE
add build task

### ISSUE THREAD

**Issue by moebiusmania** [contactlab/contactlab-pattern-library#17]
this task must:
- [ ] minify + concat all .css files
- [ ] minify + concat all .js global files (libraries)
- [ ] vulcanize all the Polymer components
- [ ] create a /dist folder
- [ ] concatenate this action to deploy one to update the website in one command

**Comment by Ryhazerus** [comment]
Task completed:

- [x] minify + concat all .css files<br/>
css in index has also been updated to include the 1 bundled css  file
- [ ]  minify + concat all .js global files (libraries) 
Files have been concatenated but not minified due to es6 issues with uglify, I can transpile it with babel first and then minify it, but not sure if worth it at this point considering it might be implemented soon .

- [x]  vulcanize all the Polymer components
- [x]  create a /dist folder

- [x]  concatenate this action to deploy one to update the website in one command

Should I submit a pull request on the develop branch?

**Comment by moebiusmania** [comment]
hi @Ryhazerus , yes send a PR on the **develop** branch so I can check your work and eventually align it to some internal conventions. Thanks!
